config/routes.rb
Rails.application.routes.draw do
  resources :tree_measurements
  resources :species
  resources :plots
  resources :transects
  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tree_measurement.rb
class TreeMeasurement < ApplicationRecord
  belongs_to :species
  belongs_to :plot
  has_one    :transect,         through: :plot

  validates  :measurement_date, presence: true
  validates  :plot_id,          uniqueness:
                                  { scope: [:species_id, :subquadrat,
                                            :tree_label, :measurement_date] }
end

app/controllers/tree_measurements_controller.rb
class TreeMeasurementsController < ApplicationController
  before_action :set_tree_measurement, only: [:show, :edit, :update, :destroy]

  # GET /tree_measurements
  # GET /tree_measurements.json
  def index
    @tree_measurements = TreeMeasurement.all
  end

  # GET /tree_measurements/1
  # GET /tree_measurements/1.json
  def show
  end

  # GET /tree_measurements/new
  def new
    @tree_measurement = TreeMeasurement.new
  end

  # GET /tree_measurements/1/edit
  def edit
  end

  # POST /tree_measurements
  # POST /tree_measurements.json
  def create
    @tree_measurement = TreeMeasurement.new(tree_measurement_params)

    respond_to do |format|
      if @tree_measurement.save
        format.html { redirect_to @tree_measurement, notice: 'Tree measurement was successfully created.' }
        format.json { render :show, status: :created, location: @tree_measurement }
      else
        format.html { render :new }
        format.json { render json: @tree_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tree_measurements/1
  # PATCH/PUT /tree_measurements/1.json
  def update
    respond_to do |format|
      if @tree_measurement.update(tree_measurement_params)
        format.html { redirect_to @tree_measurement, notice: 'Tree measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree_measurement }
      else
        format.html { render :edit }
        format.json { render json: @tree_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tree_measurements/1
  # DELETE /tree_measurements/1.json
  def destroy
    @tree_measurement.destroy
    respond_to do |format|
      format.html { redirect_to tree_measurements_url, notice: 'Tree measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree_measurement
      @tree_measurement = TreeMeasurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_measurement_params
      params.require(:tree_measurement).permit(:circumfrence_cm, :measurement_date, :subquadrat, :tree_label, :species_id, :plot_id)
    end
end

app/helpers/tree_measurements_helper.rb
module TreeMeasurementsHelper
end

app/views/tree_measurements/_form.html.erb
<%= form_with(model: tree_measurement, local: true) do |form| %>
  <% if tree_measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tree_measurement.errors.count, "error") %> prohibited this tree_measurement from being saved:</h2>

      <ul>
      <% tree_measurement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :circumfrence_cm %>
    <%= form.number_field :circumfrence_cm, id: :tree_measurement_circumfrence_cm %>
  </div>

  <div class="field">
    <%= form.label :measurement_date %>
    <%= form.date_select :measurement_date, id: :tree_measurement_measurement_date %>
  </div>

  <div class="field">
    <%= form.label :subquadrat %>
    <%= form.text_field :subquadrat, id: :tree_measurement_subquadrat %>
  </div>

  <div class="field">
    <%= form.label :tree_label %>
    <%= form.text_field :tree_label, id: :tree_measurement_tree_label %>
  </div>

  <div class="field">
    <%= form.label :species_id %>
    <%= form.text_field :species_id, id: :tree_measurement_species_id %>
  </div>

  <div class="field">
    <%= form.label :plot_id %>
    <%= form.text_field :plot_id, id: :tree_measurement_plot_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tree_measurements/edit.html.erb
<h1>Editing Tree Measurement</h1>

<%= render 'form', tree_measurement: @tree_measurement %>

<%= link_to 'Show', @tree_measurement %> |
<%= link_to 'Back', tree_measurements_path %>

app/views/tree_measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tree Measurements</h1>

<table>
  <thead>
    <tr>
      <th>Circumfrence cm</th>
      <th>Measurement date</th>
      <th>Subquadrat</th>
      <th>Tree label</th>
      <th>Species</th>
      <th>Plot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tree_measurements.each do |tree_measurement| %>
      <tr>
        <td><%= tree_measurement.circumfrence_cm %></td>
        <td><%= tree_measurement.measurement_date %></td>
        <td><%= tree_measurement.subquadrat %></td>
        <td><%= tree_measurement.tree_label %></td>
        <td><%= tree_measurement.species %></td>
        <td><%= tree_measurement.plot %></td>
        <td><%= link_to 'Show', tree_measurement %></td>
        <td><%= link_to 'Edit', edit_tree_measurement_path(tree_measurement) %></td>
        <td><%= link_to 'Destroy', tree_measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree Measurement', new_tree_measurement_path %>

app/views/tree_measurements/new.html.erb
<h1>New Tree Measurement</h1>

<%= render 'form', tree_measurement: @tree_measurement %>

<%= link_to 'Back', tree_measurements_path %>

app/views/tree_measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Circumfrence cm:</strong>
  <%= @tree_measurement.circumfrence_cm %>
</p>

<p>
  <strong>Measurement date:</strong>
  <%= @tree_measurement.measurement_date %>
</p>

<p>
  <strong>Subquadrat:</strong>
  <%= @tree_measurement.subquadrat %>
</p>

<p>
  <strong>Tree label:</strong>
  <%= @tree_measurement.tree_label %>
</p>

<p>
  <strong>Species:</strong>
  <%= @tree_measurement.species %>
</p>

<p>
  <strong>Plot:</strong>
  <%= @tree_measurement.plot %>
</p>

<%= link_to 'Edit', edit_tree_measurement_path(@tree_measurement) %> |
<%= link_to 'Back', tree_measurements_path %>