config/routes.rb
Rails.application.routes.draw do
  resources :tree_measurements
  resources :species
  resources :plots
  resources :transects
  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plot.rb
class Plot < ApplicationRecord
  belongs_to :transect
  has_many   :tree_measurements,  dependent: :destroy
  has_many   :species,            through:   :tree_meausrements

  validates :plot_code,         presence: true, uniqueness: true
  validates :plot_name,         presence: true
  validates :plot_slope,        numericality: { only_integer: true }
  validates :plot_aspect,       numericality: { only_integer: true }
  validates :plot_elevation_m,  presence: true, numericality: {
                                        only_integer: true }
  validates :plot_latitude,     presence: true, numericality: {
                                        less_than_or_equal_to:     90,
                                        greater_than_or_equal_to: -90 }
  validates :plot_longitude,    presence: true, numericality: {
                                        less_than_or_equal_to:     180,
                                        greater_than_or_equal_to: -180 }

end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  before_action :set_plot, only: [:show, :edit, :update, :destroy]

  # GET /plots
  # GET /plots.json
  def index
    @plots = Plot.all
  end

  # GET /plots/1
  # GET /plots/1.json
  def show
  end

  # GET /plots/new
  def new
    @plot = Plot.new
  end

  # GET /plots/1/edit
  def edit
  end

  # POST /plots
  # POST /plots.json
  def create
    @plot = Plot.new(plot_params)

    respond_to do |format|
      if @plot.save
        format.html { redirect_to @plot, notice: 'Plot was successfully created.' }
        format.json { render :show, status: :created, location: @plot }
      else
        format.html { render :new }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plots/1
  # PATCH/PUT /plots/1.json
  def update
    respond_to do |format|
      if @plot.update(plot_params)
        format.html { redirect_to @plot, notice: 'Plot was successfully updated.' }
        format.json { render :show, status: :ok, location: @plot }
      else
        format.html { render :edit }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plots/1
  # DELETE /plots/1.json
  def destroy
    @plot.destroy
    respond_to do |format|
      format.html { redirect_to plots_url, notice: 'Plot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plot
      @plot = Plot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plot_params
      params.require(:plot).permit(:plot_code, :plot_name, :references)
    end
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/views/plots/_form.html.erb
<%= form_with(model: plot, local: true) do |form| %>
  <% if plot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plot.errors.count, "error") %> prohibited this plot from being saved:</h2>

      <ul>
      <% plot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plot_code %>
    <%= form.text_field :plot_code, id: :plot_plot_code %>
  </div>

  <div class="field">
    <%= form.label :plot_name %>
    <%= form.text_field :plot_name, id: :plot_plot_name %>
  </div>

  <div class="field">
    <%= form.label :references %>
    <%= form.text_field :references, id: :plot_references %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plots/edit.html.erb
<h1>Editing Plot</h1>

<%= render 'form', plot: @plot %>

<%= link_to 'Show', @plot %> |
<%= link_to 'Back', plots_path %>

app/views/plots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plots</h1>

<table>
  <thead>
    <tr>
      <th>Plot code</th>
      <th>Plot name</th>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plots.each do |plot| %>
      <tr>
        <td><%= plot.plot_code %></td>
        <td><%= plot.plot_name %></td>
        <td><%= plot.references %></td>
        <td><%= link_to 'Show', plot %></td>
        <td><%= link_to 'Edit', edit_plot_path(plot) %></td>
        <td><%= link_to 'Destroy', plot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plot', new_plot_path %>

app/views/plots/new.html.erb
<h1>New Plot</h1>

<%= render 'form', plot: @plot %>

<%= link_to 'Back', plots_path %>

app/views/plots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plot code:</strong>
  <%= @plot.plot_code %>
</p>

<p>
  <strong>Plot name:</strong>
  <%= @plot.plot_name %>
</p>

<p>
  <strong>References:</strong>
  <%= @plot.references %>
</p>

<%= link_to 'Edit', edit_plot_path(@plot) %> |
<%= link_to 'Back', plots_path %>