config/routes.rb
Rails.application.routes.draw do
  resources :tree_measurements
  resources :species
  resources :plots
  resources :transects
  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]

  # GET /species
  # GET /species.json
  def index
    @species = Species.all
  end

  # GET /species/1
  # GET /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(:species_code, :species_name)
    end
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/species/_form.html.erb
<%= form_with(model: species, local: true) do |form| %>
  <% if species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% species.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :species_code %>
    <%= form.text_field :species_code, id: :species_species_code %>
  </div>

  <div class="field">
    <%= form.label :species_name %>
    <%= form.text_field :species_name, id: :species_species_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form', species: @species %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Species</h1>

<table>
  <thead>
    <tr>
      <th>Species code</th>
      <th>Species name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr>
        <td><%= species.species_code %></td>
        <td><%= species.species_name %></td>
        <td><%= link_to 'Show', species %></td>
        <td><%= link_to 'Edit', edit_species_path(species) %></td>
        <td><%= link_to 'Destroy', species, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Species', new_species_path %>

app/views/species/new.html.erb
<h1>New Species</h1>

<%= render 'form', species: @species %>

<%= link_to 'Back', species_index_path %>

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Species code:</strong>
  <%= @species.species_code %>
</p>

<p>
  <strong>Species name:</strong>
  <%= @species.species_name %>
</p>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>