config/routes.rb
Rails.application.routes.draw do
  resources :tree_measurements
  resources :species
  resources :plots
  resources :transects
  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transect.rb
class Transect < ApplicationRecord
  has_many :plots,              dependent: :destroy
  # doesn't do nested deletes on purpose (protect against probs with join tables)
  has_many :tree_meausrements,  through:   :plots
  has_many :species,            through:   :tree_meausrements
  # has_many :transect_admin_editor, dependent: :destroy
  # has_many :admins,            through: :transect_admin_editor

  validates :transect_code, presence: true, uniqueness: true
  validates :transect_name, presence: true
  validates :target_slope,  numericality: { only_integer: true }
  validates :target_aspect, numericality: { only_integer: true }
end

app/controllers/transects_controller.rb
class TransectsController < ApplicationController
  before_action :set_transect, only: [:show, :edit, :update, :destroy]

  # GET /transects
  # GET /transects.json
  def index
    @transects = Transect.all
  end

  # GET /transects/1
  # GET /transects/1.json
  def show
  end

  # GET /transects/new
  def new
    @transect = Transect.new
  end

  # GET /transects/1/edit
  def edit
  end

  # POST /transects
  # POST /transects.json
  def create
    @transect = Transect.new(transect_params)

    respond_to do |format|
      if @transect.save
        format.html { redirect_to @transect, notice: 'Transect was successfully created.' }
        format.json { render :show, status: :created, location: @transect }
      else
        format.html { render :new }
        format.json { render json: @transect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transects/1
  # PATCH/PUT /transects/1.json
  def update
    respond_to do |format|
      if @transect.update(transect_params)
        format.html { redirect_to @transect, notice: 'Transect was successfully updated.' }
        format.json { render :show, status: :ok, location: @transect }
      else
        format.html { render :edit }
        format.json { render json: @transect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transects/1
  # DELETE /transects/1.json
  def destroy
    @transect.destroy
    respond_to do |format|
      format.html { redirect_to transects_url, notice: 'Transect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transect
      @transect = Transect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transect_params
      params.require(:transect).permit(:transect_code, :transect_name)
    end
end

app/helpers/transects_helper.rb
module TransectsHelper
end

app/views/transects/_form.html.erb
<%= form_with(model: transect, local: true) do |form| %>
  <% if transect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transect.errors.count, "error") %> prohibited this transect from being saved:</h2>

      <ul>
      <% transect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :transect_code %>
    <%= form.text_field :transect_code, id: :transect_transect_code %>
  </div>

  <div class="field">
    <%= form.label :transect_name %>
    <%= form.text_field :transect_name, id: :transect_transect_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transects/edit.html.erb
<h1>Editing Transect</h1>

<%= render 'form', transect: @transect %>

<%= link_to 'Show', @transect %> |
<%= link_to 'Back', transects_path %>

app/views/transects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transects</h1>

<table>
  <thead>
    <tr>
      <th>Transect code</th>
      <th>Transect name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transects.each do |transect| %>
      <tr>
        <td><%= transect.transect_code %></td>
        <td><%= transect.transect_name %></td>
        <td><%= link_to 'Show', transect %></td>
        <td><%= link_to 'Edit', edit_transect_path(transect) %></td>
        <td><%= link_to 'Destroy', transect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transect', new_transect_path %>

app/views/transects/new.html.erb
<h1>New Transect</h1>

<%= render 'form', transect: @transect %>

<%= link_to 'Back', transects_path %>

app/views/transects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transect code:</strong>
  <%= @transect.transect_code %>
</p>

<p>
  <strong>Transect name:</strong>
  <%= @transect.transect_name %>
</p>

<%= link_to 'Edit', edit_transect_path(@transect) %> |
<%= link_to 'Back', transects_path %>